timeout: 1200s
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/live-agent-backend', '.' ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/live-agent-backend' ]

# Deploy container image to Cloud Run
# note: session affinity is enabled to ensure that the same instance is used for the same user's requests
# note: timeout 15 minutes which is the max live-api can handle
# note: concurrency 1 such that global state is not shared between requests
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'live-agent-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/live-agent-backend'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'PROJECT_ID=${PROJECT_ID},LOG_LEVEL=INFO,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_GENAI_USE_VERTEXAI=1,DEMO_TYPE=retail,VOICE_VERTEX_API=Aoede,LANGUAGE=en-GB'
  - '--service-account'
  - 'live-agent-backend@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--session-affinity'
  - '--timeout'
  - '900'
  - '--concurrency'
  - '1'
  - '--cpu'
  - '2'
  - '--memory'
  - '2Gi'

images:
- 'gcr.io/$PROJECT_ID/live-agent-backend'
