from datetime import datetime
import random
from config.config import LANGUAGE, GCS_ASSETS_BASE_URL

DEFAULT_LANGUAGE = LANGUAGE or "English (United Kingdom)"

# Base URL for product images -- avoids repeating the full GCS path 150+ times
_IMG = f"{GCS_ASSETS_BASE_URL}/products"


class RetailContext:
    # Product Catalog - Available products in store (Latest Models 2024-2025)
    PRODUCT_CATALOG = [
        # Electronics - Smartphones & Tablets (Latest 2024-2025 Models)
        # Apple iPhone 16 Series - Latest
        {
            "product_id": "APPLE-IPHONE-16",
            "sku": "1000001",
            "name": "Apple iPhone 16 128GB",
            "category": "Smartphones",
            "price": 999.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_iphone_16.jpg",
        },
        {
            "product_id": "APPLE-IPHONE-16-PLUS",
            "sku": "1000002",
            "name": "Apple iPhone 16 Plus 256GB",
            "category": "Smartphones",
            "price": 1099.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_iphone_16_plus.jpg",
        },
        {
            "product_id": "APPLE-IPHONE-16-PRO",
            "sku": "1000003",
            "name": "Apple iPhone 16 Pro 256GB",
            "category": "Smartphones",
            "price": 1199.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_iphone_16_pro.jpg",
        },
        {
            "product_id": "APPLE-IPHONE-16-PRO-MAX",
            "sku": "1000004",
            "name": "Apple iPhone 16 Pro Max 512GB",
            "category": "Smartphones",
            "price": 1399.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_iphone_16_pro_max.jpg",
        },
        # Google Pixel 9 Series - Latest
        {
            "product_id": "GOOGLE-PIXEL-9",
            "sku": "1000005",
            "name": "Google Pixel 9 128GB",
            "category": "Smartphones",
            "price": 799.00,
            "in_stock": True,
            "image_url": f"{_IMG}/google_pixel_9.jpg",
        },
        {
            "product_id": "GOOGLE-PIXEL-9-PRO",
            "sku": "1000006",
            "name": "Google Pixel 9 Pro 256GB",
            "category": "Smartphones",
            "price": 899.00,
            "in_stock": True,
            "image_url": f"{_IMG}/google_pixel_9_pro.jpg",
        },
        {
            "product_id": "GOOGLE-PIXEL-9-PRO-XL",
            "sku": "1000007",
            "name": "Google Pixel 9 Pro XL 512GB",
            "category": "Smartphones",
            "price": 1099.00,
            "in_stock": True,
            "image_url": f"{_IMG}/google_pixel_9_pro_xl.jpg",
        },
        {
            "product_id": "GOOGLE-PIXEL-9-PRO-FOLD",
            "sku": "1000008",
            "name": "Google Pixel 9 Pro Fold",
            "category": "Smartphones",
            "price": 1799.00,
            "in_stock": True,
            "image_url": f"{_IMG}/google_pixel_9_pro_fold.jpg",
        },
        # Samsung Galaxy S24 Series - Latest
        {
            "product_id": "SAMSUNG-GALAXY-S24",
            "sku": "1000009",
            "name": "Samsung Galaxy S24 256GB",
            "category": "Smartphones",
            "price": 899.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_galaxy_s24.jpg",
        },
        {
            "product_id": "SAMSUNG-GALAXY-S24-PLUS",
            "sku": "1000010",
            "name": "Samsung Galaxy S24 Plus 512GB",
            "category": "Smartphones",
            "price": 1099.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_galaxy_s24_plus.jpg",
        },
        {
            "product_id": "SAMSUNG-GALAXY-S24-ULTRA",
            "sku": "1000011",
            "name": "Samsung Galaxy S24 Ultra 512GB",
            "category": "Smartphones",
            "price": 1299.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_galaxy_s24_ultra.jpg",
        },
        {
            "product_id": "SAMSUNG-GALAXY-Z-FOLD6",
            "sku": "1000012",
            "name": "Samsung Galaxy Z Fold 6",
            "category": "Smartphones",
            "price": 1899.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_galaxy_z_fold6.jpg",
        },
        {
            "product_id": "SAMSUNG-GALAXY-Z-FLIP6",
            "sku": "1000013",
            "name": "Samsung Galaxy Z Flip 6",
            "category": "Smartphones",
            "price": 1099.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_galaxy_z_flip6.jpg",
        },
        # Latest Tablets
        {
            "product_id": "APPLE-IPAD-PRO-M4",
            "sku": "1000014",
            "name": "Apple iPad Pro M4 13-inch 512GB",
            "category": "Tablets",
            "price": 1499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_ipad_pro_m4.jpg",
        },
        {
            "product_id": "APPLE-IPAD-AIR-M2",
            "sku": "1000015",
            "name": "Apple iPad Air M2 11-inch 256GB",
            "category": "Tablets",
            "price": 699.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_ipad_air_m2.jpg",
        },
        {
            "product_id": "SAMSUNG-TAB-S10-ULTRA",
            "sku": "1000016",
            "name": "Samsung Galaxy Tab S10 Ultra",
            "category": "Tablets",
            "price": 1199.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_tab_s10_ultra.jpg",
        },
        {
            "product_id": "SAMSUNG-TAB-S10-PLUS",
            "sku": "1000017",
            "name": "Samsung Galaxy Tab S10 Plus",
            "category": "Tablets",
            "price": 899.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_tab_s10_plus.jpg",
        },
        # Electronics - TVs & Displays (Latest 2024-2025 Models)
        {
            "product_id": "SAMSUNG-QLED-QN90D-65",
            "sku": "2000001",
            "name": "Samsung QN90D Neo QLED 4K TV 65-inch (2024)",
            "category": "TVs",
            "price": 1799.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_qled_qn90d_65.jpg",
        },
        {
            "product_id": "SAMSUNG-QLED-QN85D-55",
            "sku": "2000002",
            "name": "Samsung QN85D Neo QLED 4K TV 55-inch (2024)",
            "category": "TVs",
            "price": 1399.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_qled_qn85d_55.jpg",
        },
        {
            "product_id": "LG-OLED-C4-55",
            "sku": "2000003",
            "name": "LG OLED evo C4 55-inch 4K TV (2024)",
            "category": "TVs",
            "price": 1599.00,
            "in_stock": True,
            "image_url": f"{_IMG}/lg_oled_c4_55.jpg",
        },
        {
            "product_id": "LG-OLED-G4-65",
            "sku": "2000004",
            "name": "LG OLED evo G4 65-inch 4K TV (2024)",
            "category": "TVs",
            "price": 2499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/lg_oled_g4_65.jpg",
        },
        {
            "product_id": "SONY-BRAVIA-XR-A95L",
            "sku": "2000005",
            "name": "Sony BRAVIA XR A95L OLED 65-inch (2024)",
            "category": "TVs",
            "price": 2799.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sony_bravia_xr_a95l.jpg",
        },
        {
            "product_id": "SONY-BRAVIA-9-75",
            "sku": "2000006",
            "name": "Sony BRAVIA 9 Mini LED 75-inch (2024)",
            "category": "TVs",
            "price": 3299.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sony_bravia_9_75.jpg",
        },
        {
            "product_id": "SAM-TV-QE55QN90B",
            "sku": "2789123",
            "name": "Samsung QE55QN90B Neo QLED TV",
            "category": "TVs",
            "price": 1199.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sam_tv_qe55qn90b.jpg",
        },
        # Electronics - Audio (Latest 2024-2025 Models)
        {
            "product_id": "SONY-WH1000XM6",
            "sku": "3000001",
            "name": "Sony WH-1000XM6 Noise-Cancelling Headphones (2024)",
            "category": "Audio",
            "price": 399.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sony_wh1000xm6.jpg",
        },
        {
            "product_id": "SONY-WH1000XM5S",
            "sku": "2812345",
            "name": "Sony WH-1000XM5 Noise-Cancelling Headphones",
            "category": "Audio",
            "price": 349.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sony_wh1000xm5s.jpg",
        },
        {
            "product_id": "APPLE-AIRPODS-PRO-2-USBC",
            "sku": "3000002",
            "name": "Apple AirPods Pro 2 with USB-C (2024)",
            "category": "Audio",
            "price": 249.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_airpods_pro_2_usbc.jpg",
        },
        {
            "product_id": "APPLE-AIRPODS-MAX-2",
            "sku": "3000003",
            "name": "Apple AirPods Max 2nd Gen USB-C (2024)",
            "category": "Audio",
            "price": 549.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_airpods_max_2.jpg",
        },
        {
            "product_id": "BOSE-QC-ULTRA",
            "sku": "3000004",
            "name": "Bose QuietComfort Ultra Headphones (2024)",
            "category": "Audio",
            "price": 429.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bose_qc_ultra.jpg",
        },
        {
            "product_id": "SONOS-ARC-ULTRA",
            "sku": "3000005",
            "name": "Sonos Arc Ultra Soundbar (2024)",
            "category": "Audio",
            "price": 999.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sonos_arc_ultra.jpg",
        },
        {
            "product_id": "SONOS-BEAM-GEN2",
            "sku": "3000006",
            "name": "Sonos Beam Gen 2 Soundbar",
            "category": "Audio",
            "price": 449.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sonos_beam_gen2.jpg",
        },
        # Computers & Accessories (Latest 2024-2025 Models)
        {
            "product_id": "APPLE-MACBOOK-AIR-M4",
            "sku": "4000001",
            "name": "Apple MacBook Air M4 13-inch 16GB/512GB (2025)",
            "category": "Laptops",
            "price": 1499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_macbook_air_m4.jpg",
        },
        {
            "product_id": "APPLE-MACBOOK-PRO-M4",
            "sku": "4000002",
            "name": "Apple MacBook Pro M4 14-inch 24GB/1TB (2024)",
            "category": "Laptops",
            "price": 2299.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_macbook_pro_m4.jpg",
        },
        {
            "product_id": "APPLE-MACBOOK-PRO-M4-MAX",
            "sku": "4000003",
            "name": "Apple MacBook Pro M4 Max 16-inch (2024)",
            "category": "Laptops",
            "price": 3499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_macbook_pro_m4_max.jpg",
        },
        {
            "product_id": "DELL-XPS-15-9530",
            "sku": "4000004",
            "name": "Dell XPS 15 9530 Intel Ultra 7 (2024)",
            "category": "Laptops",
            "price": 1799.00,
            "in_stock": True,
            "image_url": f"{_IMG}/dell_xps_15_9530.jpg",
        },
        {
            "product_id": "LENOVO-THINKPAD-X1-GEN12",
            "sku": "4000005",
            "name": "Lenovo ThinkPad X1 Carbon Gen 12 (2024)",
            "category": "Laptops",
            "price": 1999.00,
            "in_stock": True,
            "image_url": f"{_IMG}/lenovo_thinkpad_x1_gen12.jpg",
        },
        {
            "product_id": "MICROSOFT-SURFACE-LAPTOP-7",
            "sku": "4000006",
            "name": "Microsoft Surface Laptop 7 Snapdragon X Elite (2024)",
            "category": "Laptops",
            "price": 1599.00,
            "in_stock": True,
            "image_url": f"{_IMG}/microsoft_surface_laptop_7.jpg",
        },
        {
            "product_id": "LOGI-MX-MASTER3S",
            "sku": "2754678",
            "name": "Logitech MX Master 3S Performance Mouse",
            "category": "Accessories",
            "price": 105.00,
            "in_stock": True,
            "image_url": f"{_IMG}/logi_mx_master3s.jpg",
        },
        {
            "product_id": "LOGITECH-MX-KEYS",
            "sku": "4000004",
            "name": "Logitech MX Keys Wireless Keyboard",
            "category": "Accessories",
            "price": 119.00,
            "in_stock": True,
            "image_url": f"{_IMG}/logitech_mx_keys.jpg",
        },
        {
            "product_id": "ANKER-POWERCORE-20K",
            "sku": "2699887",
            "name": "Anker PowerCore III 20000mAh Power Bank",
            "category": "Accessories",
            "price": 49.00,
            "in_stock": True,
            "image_url": f"{_IMG}/anker_powercore_20k.jpg",
        },
        # Fashion - Footwear
        {
            "product_id": "ADIDAS-SNEAKER-ORIG",
            "sku": "5000001",
            "name": "Adidas Originals Sneaker",
            "category": "Footwear",
            "price": 99.00,
            "in_stock": True,
            "image_url": f"{_IMG}/adidas_sneaker_orig.jpg",
        },
        {
            "product_id": "NIKE-AIR-MAX-90",
            "sku": "5000002",
            "name": "Nike Air Max 90",
            "category": "Footwear",
            "price": 129.00,
            "in_stock": True,
            "image_url": f"{_IMG}/nike_air_max_90.jpg",
        },
        {
            "product_id": "NIKE-REVOLUTION-6",
            "sku": "5000005",
            "name": "Nike Revolution 6 Running Shoes",
            "category": "Footwear",
            "price": 89.00,
            "in_stock": True,
            "image_url": f"{_IMG}/nike_revolution_6.jpg",
        },
        {
            "product_id": "CONVERSE-CHUCK-TAYLOR",
            "sku": "5000003",
            "name": "Converse Chuck Taylor All Star",
            "category": "Footwear",
            "price": 65.00,
            "in_stock": True,
            "image_url": f"{_IMG}/converse_chuck_taylor.jpg",
        },
        {
            "product_id": "PUMA-SUEDE-CLASSIC",
            "sku": "5000004",
            "name": "Puma Suede Classic",
            "category": "Footwear",
            "price": 75.00,
            "in_stock": True,
            "image_url": f"{_IMG}/puma_suede_classic.jpg",
        },
        # Fashion - Clothing
        {
            "product_id": "LEVIS-501-JEANS",
            "sku": "6000001",
            "name": "LEVI'S 501 Original Jeans",
            "category": "Clothing",
            "price": 89.00,
            "in_stock": False,
            "image_url": f"{_IMG}/levis_501_jeans.jpg",
        },
        {
            "product_id": "NIKE-TECH-FLEECE",
            "sku": "6000002",
            "name": "Nike Tech Fleece Hoodie",
            "category": "Clothing",
            "price": 119.00,
            "in_stock": True,
            "image_url": f"{_IMG}/nike_tech_fleece.jpg",
        },
        {
            "product_id": "ADIDAS-TRACK-JACKET",
            "sku": "6000003",
            "name": "Adidas Originals Track Jacket",
            "category": "Clothing",
            "price": 85.00,
            "in_stock": True,
            "image_url": f"{_IMG}/adidas_track_jacket.jpg",
        },
        {
            "product_id": "TOMMY-HILFIGER-POLO",
            "sku": "6000004",
            "name": "Tommy Hilfiger Classic Polo",
            "category": "Clothing",
            "price": 69.00,
            "in_stock": True,
            "image_url": f"{_IMG}/tommy_hilfiger_polo.jpg",
        },
        # Home & Kitchen
        {
            "product_id": "WMF-COFFEEMACHINE",
            "sku": "7000001",
            "name": "WMF Coffee Machine",
            "category": "Kitchen",
            "price": 749.00,
            "in_stock": True,
            "image_url": f"{_IMG}/wmf_coffeemachine.jpg",
        },
        {
            "product_id": "KITCHENAID-MIXER",
            "sku": "7000002",
            "name": "KitchenAid Stand Mixer",
            "category": "Kitchen",
            "price": 449.00,
            "in_stock": True,
            "image_url": f"{_IMG}/kitchenaid_mixer.jpg",
        },
        {
            "product_id": "DYSON-V15-VACUUM",
            "sku": "7000003",
            "name": "Dyson V15 Detect Cordless Vacuum",
            "category": "Home",
            "price": 649.00,
            "in_stock": True,
            "image_url": f"{_IMG}/dyson_v15_vacuum.jpg",
        },
        {
            "product_id": "NESPRESSO-VERTUO",
            "sku": "7000004",
            "name": "Nespresso Vertuo Next",
            "category": "Kitchen",
            "price": 169.00,
            "in_stock": True,
            "image_url": f"{_IMG}/nespresso_vertuo.jpg",
        },
        {
            "product_id": "PHILIPS-AIR-FRYER",
            "sku": "7000005",
            "name": "Philips Airfryer XXL",
            "category": "Kitchen",
            "price": 299.00,
            "in_stock": True,
            "image_url": f"{_IMG}/philips_air_fryer.jpg",
        },
        # Smart Home
        {
            "product_id": "NEST-THERMOSTAT",
            "sku": "8000001",
            "name": "Google Nest Learning Thermostat",
            "category": "Smart Home",
            "price": 249.00,
            "in_stock": True,
            "image_url": f"{_IMG}/nest_thermostat.jpg",
        },
        {
            "product_id": "RING-DOORBELL-PRO",
            "sku": "8000002",
            "name": "Ring Video Doorbell Pro 2",
            "category": "Smart Home",
            "price": 269.00,
            "in_stock": True,
            "image_url": f"{_IMG}/ring_doorbell_pro.jpg",
        },
        {
            "product_id": "PHILIPS-HUE-KIT",
            "sku": "8000003",
            "name": "Philips Hue White & Color Starter Kit",
            "category": "Smart Home",
            "price": 199.00,
            "in_stock": True,
            "image_url": f"{_IMG}/philips_hue_kit.jpg",
        },
        {
            "product_id": "AMAZON-ECHO-SHOW",
            "sku": "8000004",
            "name": "Amazon Echo Show 10",
            "category": "Smart Home",
            "price": 249.00,
            "in_stock": True,
            "image_url": f"{_IMG}/amazon_echo_show.jpg",
        },
        # Gaming
        {
            "product_id": "PS5-CONSOLE",
            "sku": "9000001",
            "name": "PlayStation 5 Console",
            "category": "Gaming",
            "price": 499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/ps5_console.jpg",
        },
        {
            "product_id": "XBOX-SERIES-X",
            "sku": "9000002",
            "name": "Xbox Series X",
            "category": "Gaming",
            "price": 499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/xbox_series_x.jpg",
        },
        {
            "product_id": "NINTENDO-SWITCH-OLED",
            "sku": "9000003",
            "name": "Nintendo Switch OLED",
            "category": "Gaming",
            "price": 349.00,
            "in_stock": True,
            "image_url": f"{_IMG}/nintendo_switch_oled.jpg",
        },
        {
            "product_id": "STEAM-DECK",
            "sku": "9000004",
            "name": "Steam Deck 512GB",
            "category": "Gaming",
            "price": 649.00,
            "in_stock": True,
            "image_url": f"{_IMG}/steam_deck.jpg",
        },
        {
            "product_id": "GAMEMAX-PC-RTX4070",
            "sku": "9000005",
            "name": "GAMEMAX Gaming PC RTX 4070",
            "category": "Gaming",
            "price": 1599.00,
            "in_stock": True,
            "image_url": f"{_IMG}/gamemax_pc_rtx4070.jpg",
        },
        # Cameras & Photography
        {
            "product_id": "CANON-EOS-R6",
            "sku": "10000001",
            "name": "Canon EOS R6 Mark II",
            "category": "Cameras",
            "price": 2499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/canon_eos_r6.jpg",
        },
        {
            "product_id": "SONY-A7-IV",
            "sku": "10000002",
            "name": "Sony Alpha 7 IV",
            "category": "Cameras",
            "price": 2499.00,
            "in_stock": True,
            "image_url": f"{_IMG}/sony_a7_iv.jpg",
        },
        {
            "product_id": "GOPRO-HERO12",
            "sku": "10000003",
            "name": "GoPro HERO12 Black",
            "category": "Cameras",
            "price": 399.00,
            "in_stock": True,
            "image_url": f"{_IMG}/gopro_hero12.jpg",
        },
        {
            "product_id": "DJI-MINI-4-PRO",
            "sku": "10000004",
            "name": "DJI Mini 4 Pro Drone",
            "category": "Cameras",
            "price": 759.00,
            "in_stock": True,
            "image_url": f"{_IMG}/dji_mini_4_pro.jpg",
        },
        # Accessories & Cases
        {
            "product_id": "GENERIC-PIXEL-CASE",
            "sku": "1122334",
            "name": "Generic Google Pixel Case",
            "category": "Accessories",
            "price": 19.00,
            "in_stock": True,
            "image_url": f"{_IMG}/generic_pixel_case.jpg",
        },
        {
            "product_id": "GOOGLE-PIXEL9PRO-CASE",
            "sku": "11000001",
            "name": "Google Pixel 9 Pro Defender Series Case",
            "category": "Accessories",
            "price": 59.99,
            "in_stock": True,
            "image_url": f"{_IMG}/google_pixel9pro_case.jpg",
        },
        {
            "product_id": "APPLE-LEATHER-CASE",
            "sku": "11000002",
            "name": "Apple iPhone 16 Leather Case",
            "category": "Accessories",
            "price": 59.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_leather_case.jpg",
        },
        {
            "product_id": "GOOGLE-PIXEL-30W-CHARGER",
            "sku": "11000003",
            "name": "Google 30W USB-C Charger",
            "category": "Accessories",
            "price": 29.00,
            "in_stock": True,
            "image_url": f"{_IMG}/google_pixel_30w_charger.jpg",
        },
        # Wearables
        {
            "product_id": "APPLE-WATCH-SERIES-9",
            "sku": "12000001",
            "name": "Apple Watch Series 9",
            "category": "Wearables",
            "price": 399.00,
            "in_stock": True,
            "image_url": f"{_IMG}/apple_watch_series_9.jpg",
        },
        {
            "product_id": "SAMSUNG-GALAXY-WATCH6",
            "sku": "12000002",
            "name": "Samsung Galaxy Watch 6",
            "category": "Wearables",
            "price": 299.00,
            "in_stock": True,
            "image_url": f"{_IMG}/samsung_galaxy_watch6.jpg",
        },
        {
            "product_id": "FITBIT-CHARGE-6",
            "sku": "12000003",
            "name": "Fitbit Charge 6",
            "category": "Wearables",
            "price": 159.00,
            "in_stock": True,
            "image_url": f"{_IMG}/fitbit_charge_6.jpg",
        },
        # Services
        {
            "product_id": "PLUSGARANTIE-TV-3J",
            "sku": "8765432",
            "name": "Extended warranty 3 years for TV up to 1650 EUR",
            "category": "Services",
            "price": 139.00,
            "type": "service",
        },
        {
            "product_id": "PREFERRED-CARE-PHONE",
            "sku": "13000001",
            "name": "Preferred Care Protection for Smartphones",
            "category": "Services",
            "price": 99.00,
            "type": "service",
        },
        {
            "product_id": "SETUP-SERVICE-TV",
            "sku": "13000002",
            "name": "TV Installation and Setup Service",
            "category": "Services",
            "price": 149.00,
            "type": "service",
        },
        # Home Decor - Wall Art
        {
            "product_id": "WALL-ART-ABSTRACT-CANVAS",
            "sku": "14000001",
            "name": "Abstract Canvas Art 'Sunset Dreams' 120x80cm",
            "category": "Home Decor",
            "subcategory": "Wall Art",
            "price": 129.00,
            "in_stock": True,
            "style_tags": ["modern", "abstract", "warm-tones"],
            "color_palette": ["orange", "pink", "gold"],
            "room_compatibility": ["living room", "bedroom", "office"],
            "image_url": f"{_IMG}/apple_iphone_16.jpg",
        },
        {
            "product_id": "WALL-ART-BOTANICAL-PRINT",
            "sku": "14000002",
            "name": "Botanical Print Set (3 pieces) 'Tropical Leaves'",
            "category": "Home Decor",
            "subcategory": "Wall Art",
            "price": 79.00,
            "in_stock": True,
            "style_tags": ["bohemian", "natural", "tropical"],
            "color_palette": ["green", "white", "beige"],
            "room_compatibility": ["living room", "bedroom", "bathroom"],
            "image_url": f"{_IMG}/wall_art_botanical_print.jpg",
        },
        {
            "product_id": "WALL-ART-GEOMETRIC-METAL",
            "sku": "14000003",
            "name": "Geometric Metal Wall Art 'Golden Hexagons'",
            "category": "Home Decor",
            "subcategory": "Wall Art",
            "price": 159.00,
            "in_stock": True,
            "style_tags": ["modern", "geometric", "metallic"],
            "color_palette": ["gold", "black", "brass"],
            "room_compatibility": ["living room", "dining room", "entryway"],
            "image_url": f"{_IMG}/wall_art_geometric_metal.jpg",
        },
        {
            "product_id": "WALL-ART-MINIMALIST-LINE",
            "sku": "14000004",
            "name": "Minimalist Line Drawing 'Woman Portrait' 60x80cm",
            "category": "Home Decor",
            "subcategory": "Wall Art",
            "price": 89.00,
            "in_stock": True,
            "style_tags": ["minimalist", "modern", "line-art"],
            "color_palette": ["black", "white"],
            "room_compatibility": ["bedroom", "office", "bathroom"],
            "image_url": f"{_IMG}/wall_art_minimalist_line.jpg",
        },
        {
            "product_id": "WALL-ART-COASTAL-PHOTO",
            "sku": "14000005",
            "name": "Coastal Photography Print 'Ocean Waves' 100x70cm",
            "category": "Home Decor",
            "subcategory": "Wall Art",
            "price": 99.00,
            "in_stock": True,
            "style_tags": ["coastal", "natural", "calm"],
            "color_palette": ["blue", "white", "turquoise"],
            "room_compatibility": ["living room", "bedroom", "bathroom"],
            "image_url": f"{_IMG}/wall_art_coastal_photo.jpg",
        },
        # Home Decor - Lighting
        {
            "product_id": "LAMP-ARC-FLOOR-GOLD",
            "sku": "14000006",
            "name": "Arc Floor Lamp 'Modern Gold' with Marble Base",
            "category": "Home Decor",
            "subcategory": "Lighting",
            "price": 249.00,
            "in_stock": True,
            "style_tags": ["modern", "luxury", "metallic"],
            "color_palette": ["gold", "white", "marble"],
            "room_compatibility": ["living room", "reading nook", "office"],
            "image_url": f"{_IMG}/lamp_arc_floor_gold.jpg",
        },
        {
            "product_id": "LAMP-PENDANT-RATTAN",
            "sku": "14000007",
            "name": "Rattan Pendant Light 'Bohemian Sphere' 40cm",
            "category": "Home Decor",
            "subcategory": "Lighting",
            "price": 119.00,
            "in_stock": True,
            "style_tags": ["bohemian", "natural", "woven"],
            "color_palette": ["beige", "natural", "brown"],
            "room_compatibility": ["dining room", "bedroom", "entryway"],
            "image_url": f"{_IMG}/lamp_pendant_rattan.jpg",
        },
        {
            "product_id": "LAMP-TABLE-CERAMIC",
            "sku": "14000008",
            "name": "Ceramic Table Lamp 'Ocean Blue' with Linen Shade",
            "category": "Home Decor",
            "subcategory": "Lighting",
            "price": 89.00,
            "in_stock": True,
            "style_tags": ["coastal", "traditional", "ceramic"],
            "color_palette": ["blue", "white", "beige"],
            "room_compatibility": ["bedroom", "living room", "office"],
            "image_url": f"{_IMG}/lamp_table_ceramic.jpg",
        },
        {
            "product_id": "LAMP-WALL-SCONCE-BRASS",
            "sku": "14000009",
            "name": "Brass Wall Sconce Set (2 pieces) 'Industrial Chic'",
            "category": "Home Decor",
            "subcategory": "Lighting",
            "price": 149.00,
            "in_stock": True,
            "style_tags": ["industrial", "modern", "metallic"],
            "color_palette": ["brass", "black", "gold"],
            "room_compatibility": ["bedroom", "hallway", "bathroom"],
            "image_url": f"{_IMG}/lamp_wall_sconce_brass.jpg",
        },
        {
            "product_id": "LAMP-STRING-FAIRY",
            "sku": "14000010",
            "name": "LED Fairy String Lights 'Warm White' 10m",
            "category": "Home Decor",
            "subcategory": "Lighting",
            "price": 29.00,
            "in_stock": True,
            "style_tags": ["bohemian", "cozy", "ambient"],
            "color_palette": ["warm-white", "gold"],
            "room_compatibility": ["bedroom", "living room", "patio"],
            "image_url": f"{_IMG}/lamp_string_fairy.jpg",
        },
        # Home Decor - Plants & Planters
        {
            "product_id": "PLANTER-CERAMIC-WHITE-SET",
            "sku": "14000011",
            "name": "White Ceramic Planter Set (3 sizes) with Drainage",
            "category": "Home Decor",
            "subcategory": "Plants & Planters",
            "price": 59.00,
            "in_stock": True,
            "style_tags": ["minimalist", "modern", "clean"],
            "color_palette": ["white", "matte"],
            "room_compatibility": ["living room", "kitchen", "bedroom", "office"],
            "image_url": f"{_IMG}/planter_ceramic_white_set.jpg",
        },
        {
            "product_id": "PLANTER-TERRACOTTA-LARGE",
            "sku": "14000012",
            "name": "Large Terracotta Planter 'Mediterranean' 35cm",
            "category": "Home Decor",
            "subcategory": "Plants & Planters",
            "price": 45.00,
            "in_stock": True,
            "style_tags": ["bohemian", "rustic", "natural"],
            "color_palette": ["terracotta", "orange", "clay"],
            "room_compatibility": ["living room", "patio", "entryway"],
            "image_url": f"{_IMG}/planter_terracotta_large.jpg",
        },
        {
            "product_id": "PLANT-FAUX-MONSTERA",
            "sku": "14000013",
            "name": "Artificial Monstera Plant 'Deliciosa' 120cm with Pot",
            "category": "Home Decor",
            "subcategory": "Plants & Planters",
            "price": 89.00,
            "in_stock": True,
            "style_tags": ["tropical", "bohemian", "green"],
            "color_palette": ["green", "natural"],
            "room_compatibility": ["living room", "bedroom", "office"],
            "image_url": f"{_IMG}/plant_faux_monstera.jpg",
        },
        {
            "product_id": "PLANTER-HANGING-MACRAME",
            "sku": "14000014",
            "name": "Macrame Hanging Planter 'Bohemian Dream' Set of 2",
            "category": "Home Decor",
            "subcategory": "Plants & Planters",
            "price": 39.00,
            "in_stock": True,
            "style_tags": ["bohemian", "handmade", "woven"],
            "color_palette": ["beige", "cream", "natural"],
            "room_compatibility": ["living room", "bedroom", "patio"],
            "image_url": f"{_IMG}/planter_hanging_macrame.jpg",
        },
        {
            "product_id": "PLANT-FAUX-EUCALYPTUS",
            "sku": "14000015",
            "name": "Artificial Eucalyptus Branches (6 stems) 60cm",
            "category": "Home Decor",
            "subcategory": "Plants & Planters",
            "price": 24.00,
            "in_stock": True,
            "style_tags": ["natural", "minimalist", "greenery"],
            "color_palette": ["sage-green", "grey-green"],
            "room_compatibility": ["bedroom", "bathroom", "kitchen"],
            "image_url": f"{_IMG}/plant_faux_eucalyptus.jpg",
        },
        # Home Decor - Textiles
        {
            "product_id": "THROW-BLANKET-CHUNKY-KNIT",
            "sku": "14000016",
            "name": "Chunky Knit Throw Blanket 'Cozy Cloud' Cream 150x180cm",
            "category": "Home Decor",
            "subcategory": "Textiles",
            "price": 79.00,
            "in_stock": True,
            "style_tags": ["cozy", "minimalist", "textured"],
            "color_palette": ["cream", "beige", "ivory"],
            "room_compatibility": ["living room", "bedroom"],
            "image_url": f"{_IMG}/throw_blanket_chunky_knit.jpg",
        },
        {
            "product_id": "CUSHION-VELVET-SET",
            "sku": "14000017",
            "name": "Velvet Cushion Cover Set (4 pieces) 'Jewel Tones' 45x45cm",
            "category": "Home Decor",
            "subcategory": "Textiles",
            "price": 69.00,
            "in_stock": True,
            "style_tags": ["luxury", "modern", "rich-colors"],
            "color_palette": ["emerald", "navy", "gold", "burgundy"],
            "room_compatibility": ["living room", "bedroom"],
            "image_url": f"{_IMG}/cushion_velvet_set.jpg",
        },
        {
            "product_id": "RUG-MOROCCAN-STYLE",
            "sku": "14000018",
            "name": "Moroccan Style Area Rug 'Berber' 200x300cm Beige",
            "category": "Home Decor",
            "subcategory": "Textiles",
            "price": 299.00,
            "in_stock": True,
            "style_tags": ["bohemian", "geometric", "traditional"],
            "color_palette": ["beige", "cream", "black"],
            "room_compatibility": ["living room", "bedroom", "dining room"],
            "image_url": f"{_IMG}/rug_moroccan_style.jpg",
        },
        {
            "product_id": "CURTAIN-LINEN-NATURAL",
            "sku": "14000019",
            "name": "Natural Linen Curtain Panels (2 pieces) 'Airy' 140x260cm",
            "category": "Home Decor",
            "subcategory": "Textiles",
            "price": 119.00,
            "in_stock": True,
            "style_tags": ["minimalist", "natural", "light"],
            "color_palette": ["beige", "natural", "cream"],
            "room_compatibility": ["living room", "bedroom", "dining room"],
            "image_url": f"{_IMG}/curtain_linen_natural.jpg",
        },
        {
            "product_id": "CUSHION-BOHEMIAN-TASSELS",
            "sku": "14000020",
            "name": "Boho Cushion Covers with Tassels (3 pieces) 'Desert Sunset'",
            "category": "Home Decor",
            "subcategory": "Textiles",
            "price": 49.00,
            "in_stock": True,
            "style_tags": ["bohemian", "textured", "eclectic"],
            "color_palette": ["terracotta", "mustard", "cream"],
            "room_compatibility": ["living room", "bedroom", "reading nook"],
            "image_url": f"{_IMG}/cushion_bohemian_tassels.jpg",
        },
        # Home Decor - Decorative Objects
        {
            "product_id": "VASE-CERAMIC-MINIMALIST",
            "sku": "14000021",
            "name": "Minimalist Ceramic Vase Set (3 pieces) 'Scandi White'",
            "category": "Home Decor",
            "subcategory": "Decorative Objects",
            "price": 69.00,
            "in_stock": True,
            "style_tags": ["minimalist", "scandinavian", "clean"],
            "color_palette": ["white", "matte"],
            "room_compatibility": ["living room", "dining room", "office"],
            "image_url": f"{_IMG}/vase_ceramic_minimalist.jpg",
        },
        {
            "product_id": "MIRROR-ROUND-GOLD",
            "sku": "14000022",
            "name": "Round Gold Frame Mirror 'Sunburst' 80cm Diameter",
            "category": "Home Decor",
            "subcategory": "Decorative Objects",
            "price": 189.00,
            "in_stock": True,
            "style_tags": ["modern", "luxury", "metallic"],
            "color_palette": ["gold", "brass"],
            "room_compatibility": ["entryway", "bedroom", "bathroom"],
            "image_url": f"{_IMG}/mirror_round_gold.jpg",
        },
        {
            "product_id": "CANDLE-HOLDER-BRASS-SET",
            "sku": "14000023",
            "name": "Brass Candle Holder Set (3 heights) 'Modern Classic'",
            "category": "Home Decor",
            "subcategory": "Decorative Objects",
            "price": 59.00,
            "in_stock": True,
            "style_tags": ["modern", "metallic", "elegant"],
            "color_palette": ["brass", "gold"],
            "room_compatibility": ["dining room", "living room", "bedroom"],
            "image_url": f"{_IMG}/candle_holder_brass_set.jpg",
        },
        {
            "product_id": "TRAY-MARBLE-GOLD",
            "sku": "14000024",
            "name": "Marble and Gold Serving Tray 'Luxury' 40x30cm",
            "category": "Home Decor",
            "subcategory": "Decorative Objects",
            "price": 79.00,
            "in_stock": True,
            "style_tags": ["luxury", "modern", "marble"],
            "color_palette": ["white", "gold", "marble"],
            "room_compatibility": ["living room", "bedroom", "kitchen"],
            "image_url": f"{_IMG}/tray_marble_gold.jpg",
        },
        {
            "product_id": "SCULPTURE-ABSTRACT-CERAMIC",
            "sku": "14000025",
            "name": "Abstract Ceramic Sculpture 'Modern Art' Black Matte 35cm",
            "category": "Home Decor",
            "subcategory": "Decorative Objects",
            "price": 99.00,
            "in_stock": True,
            "style_tags": ["modern", "abstract", "sculptural"],
            "color_palette": ["black", "matte"],
            "room_compatibility": ["living room", "office", "entryway"],
            "image_url": f"{_IMG}/sculpture_abstract_ceramic.jpg",
        },
        {
            "product_id": "CLOCK-WALL-MINIMALIST",
            "sku": "14000026",
            "name": "Minimalist Wall Clock 'Silent Sweep' Walnut Wood 30cm",
            "category": "Home Decor",
            "subcategory": "Decorative Objects",
            "price": 59.00,
            "in_stock": True,
            "style_tags": ["minimalist", "modern", "wood"],
            "color_palette": ["walnut", "black", "wood"],
            "room_compatibility": ["living room", "kitchen", "office", "bedroom"],
            "image_url": f"{_IMG}/clock_wall_minimalist.jpg",
        },
        # Home Decor - Shelving & Storage
        {
            "product_id": "SHELF-FLOATING-WALNUT",
            "sku": "14000027",
            "name": "Floating Shelf Set (3 pieces) Walnut Wood 'Clean Lines'",
            "category": "Home Decor",
            "subcategory": "Shelving & Storage",
            "price": 89.00,
            "in_stock": True,
            "style_tags": ["minimalist", "modern", "wood"],
            "color_palette": ["walnut", "wood", "natural"],
            "room_compatibility": ["living room", "bedroom", "office", "bathroom"],
            "image_url": f"{_IMG}/shelf_floating_walnut.jpg",
        },
        {
            "product_id": "BASKET-STORAGE-WOVEN",
            "sku": "14000028",
            "name": "Woven Storage Basket Set (3 sizes) 'Natural Seagrass'",
            "category": "Home Decor",
            "subcategory": "Shelving & Storage",
            "price": 69.00,
            "in_stock": True,
            "style_tags": ["bohemian", "natural", "woven"],
            "color_palette": ["natural", "beige", "brown"],
            "room_compatibility": ["living room", "bedroom", "bathroom"],
            "image_url": f"{_IMG}/basket_storage_woven.jpg",
        },
        {
            "product_id": "SHELF-LADDER-BLACK",
            "sku": "14000029",
            "name": "Ladder Shelf 'Industrial Black Metal' 5 Tiers 180cm",
            "category": "Home Decor",
            "subcategory": "Shelving & Storage",
            "price": 159.00,
            "in_stock": True,
            "style_tags": ["industrial", "modern", "metal"],
            "color_palette": ["black", "metal"],
            "room_compatibility": ["living room", "office", "bedroom"],
            "image_url": f"{_IMG}/shelf_ladder_black.jpg",
        },
        {
            "product_id": "BOX-STORAGE-VELVET",
            "sku": "14000030",
            "name": "Velvet Storage Box Set (2 pieces) 'Emerald Luxury'",
            "category": "Home Decor",
            "subcategory": "Shelving & Storage",
            "price": 54.00,
            "in_stock": True,
            "style_tags": ["luxury", "modern", "rich-colors"],
            "color_palette": ["emerald", "green", "gold"],
            "room_compatibility": ["bedroom", "living room", "office"],
            "image_url": f"{_IMG}/box_storage_velvet.jpg",
        },
        # Furniture - Desks
        {
            "product_id": "DESK-CHILD-WHITE",
            "sku": "15000001",
            "name": "Children's Study Desk 'Growing Up' White 90x60cm",
            "category": "Furniture",
            "subcategory": "Desks",
            "price": 189.00,
            "in_stock": True,
            "image_url": f"{_IMG}/desk_child_white.jpg",
            "age_appropriate": ["school-age", "teen"],
            "style_tags": ["modern", "minimalist", "scandinavian"],
            "color_palette": ["white", "wood"],
            "room_compatibility": ["bedroom", "office"],
            "image_url": f"{_IMG}/desk_child_white.jpg",
        },
        {
            "product_id": "DESK-TODDLER-NATURAL",
            "sku": "15000002",
            "name": "Toddler Activity Desk 'First Steps' Natural Wood 70x50cm",
            "category": "Furniture",
            "subcategory": "Desks",
            "price": 149.00,
            "in_stock": True,
            "image_url": f"{_IMG}/desk_toddler_natural.jpg",
            "age_appropriate": ["toddler"],
            "style_tags": ["scandinavian", "natural", "minimalist"],
            "color_palette": ["wood", "natural", "beige"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/desk_toddler_natural.jpg",
        },
        {
            "product_id": "DESK-TEEN-GREY",
            "sku": "15000003",
            "name": "Teen Study Desk with Storage 'Focus' Grey 120x70cm",
            "category": "Furniture",
            "subcategory": "Desks",
            "price": 269.00,
            "in_stock": True,
            "image_url": f"{_IMG}/desk_teen_grey.jpg",
            "age_appropriate": ["teen", "adult"],
            "style_tags": ["modern", "industrial", "functional"],
            "color_palette": ["grey", "black", "metal"],
            "room_compatibility": ["bedroom", "office"],
            "image_url": f"{_IMG}/desk_teen_grey.jpg",
        },
        {
            "product_id": "DESK-ADULT-WALNUT",
            "sku": "15000004",
            "name": "Executive Desk 'Professional' Walnut Wood 140x80cm",
            "category": "Furniture",
            "subcategory": "Desks",
            "price": 449.00,
            "in_stock": True,
            "image_url": f"{_IMG}/desk_adult_walnut.jpg",
            "age_appropriate": ["adult"],
            "style_tags": ["traditional", "modern", "wood"],
            "color_palette": ["walnut", "wood", "brown"],
            "room_compatibility": ["office", "bedroom"],
            "image_url": f"{_IMG}/desk_adult_walnut.jpg",
        },
        {
            "product_id": "DESK-CORNER-WHITE",
            "sku": "15000005",
            "name": "L-Shaped Corner Desk 'Space Saver' White 150x150cm",
            "category": "Furniture",
            "subcategory": "Desks",
            "price": 329.00,
            "in_stock": True,
            "image_url": f"{_IMG}/desk_corner_white.jpg",
            "age_appropriate": ["teen", "adult"],
            "style_tags": ["modern", "minimalist", "space-saving"],
            "color_palette": ["white", "metal"],
            "room_compatibility": ["office", "bedroom"],
            "image_url": f"{_IMG}/desk_corner_white.jpg",
        },
        # Furniture - Beds
        {
            "product_id": "BED-TODDLER-HOUSE",
            "sku": "15000006",
            "name": "Toddler House Bed 'Dreamy Home' Natural Wood 140x70cm",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 289.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_toddler_house.jpg",
            "age_appropriate": ["toddler"],
            "style_tags": ["scandinavian", "playful", "natural"],
            "color_palette": ["wood", "natural", "white"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_toddler_house.jpg",
        },
        {
            "product_id": "BED-SINGLE-WHITE",
            "sku": "15000007",
            "name": "Single Bed Frame 'Classic' White 90x200cm",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 249.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_single_white.jpg",
            "age_appropriate": ["school-age", "teen"],
            "style_tags": ["minimalist", "modern", "scandinavian"],
            "color_palette": ["white", "wood"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_single_white.jpg",
        },
        {
            "product_id": "BED-TWIN-GREY",
            "sku": "15000008",
            "name": "Twin Bed with Drawers 'Storage Pro' Grey 90x200cm",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 349.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_twin_grey.jpg",
            "age_appropriate": ["school-age", "teen"],
            "style_tags": ["modern", "functional", "storage"],
            "color_palette": ["grey", "white"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_twin_grey.jpg",
        },
        {
            "product_id": "BED-BUNK-NATURAL",
            "sku": "15000009",
            "name": "Bunk Bed 'Space Master' Natural Wood Twin over Twin",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 549.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_bunk_natural.jpg",
            "age_appropriate": ["school-age", "teen"],
            "style_tags": ["scandinavian", "natural", "space-saving"],
            "color_palette": ["wood", "natural"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_bunk_natural.jpg",
        },
        {
            "product_id": "BED-LOFT-BLACK",
            "sku": "15000010",
            "name": "Loft Bed with Desk 'Study Loft' Black Metal Twin",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 429.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_loft_black.jpg",
            "age_appropriate": ["teen"],
            "style_tags": ["industrial", "modern", "space-saving"],
            "color_palette": ["black", "metal"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_loft_black.jpg",
        },
        {
            "product_id": "BED-DOUBLE-UPHOLSTERED",
            "sku": "15000011",
            "name": "Double Bed Upholstered 'Comfort' Grey Velvet 140x200cm",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 599.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_double_upholstered.jpg",
            "age_appropriate": ["adult"],
            "style_tags": ["modern", "luxury", "upholstered"],
            "color_palette": ["grey", "velvet"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_double_upholstered.jpg",
        },
        {
            "product_id": "BED-QUEEN-PLATFORM",
            "sku": "15000012",
            "name": "Platform Queen Bed 'Minimalist' Walnut 160x200cm",
            "category": "Furniture",
            "subcategory": "Beds",
            "price": 699.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bed_queen_platform.jpg",
            "age_appropriate": ["adult"],
            "style_tags": ["minimalist", "modern", "wood"],
            "color_palette": ["walnut", "wood", "brown"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/bed_queen_platform.jpg",
        },
        # Furniture - Wardrobes & Storage
        {
            "product_id": "WARDROBE-CHILD-WHITE",
            "sku": "15000013",
            "name": "Children's Wardrobe 'Growing Closet' White 2 Doors 80x180cm",
            "category": "Furniture",
            "subcategory": "Wardrobes",
            "price": 319.00,
            "in_stock": True,
            "image_url": f"{_IMG}/wardrobe_child_white.jpg",
            "age_appropriate": ["toddler", "school-age"],
            "style_tags": ["scandinavian", "minimalist", "functional"],
            "color_palette": ["white", "wood"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/wardrobe_child_white.jpg",
        },
        {
            "product_id": "WARDROBE-TEEN-GREY",
            "sku": "15000014",
            "name": "Teen Wardrobe with Mirror 'Style Station' Grey 100x200cm",
            "category": "Furniture",
            "subcategory": "Wardrobes",
            "price": 449.00,
            "in_stock": True,
            "image_url": f"{_IMG}/wardrobe_teen_grey.jpg",
            "age_appropriate": ["teen", "adult"],
            "style_tags": ["modern", "functional", "mirror"],
            "color_palette": ["grey", "white", "mirror"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/wardrobe_teen_grey.jpg",
        },
        {
            "product_id": "WARDROBE-ADULT-WALNUT",
            "sku": "15000015",
            "name": "3-Door Wardrobe 'Classic' Walnut Wood 150x200cm",
            "category": "Furniture",
            "subcategory": "Wardrobes",
            "price": 699.00,
            "in_stock": True,
            "image_url": f"{_IMG}/wardrobe_adult_walnut.jpg",
            "age_appropriate": ["adult"],
            "style_tags": ["traditional", "wood", "spacious"],
            "color_palette": ["walnut", "wood", "brown"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/wardrobe_adult_walnut.jpg",
        },
        {
            "product_id": "DRESSER-CHILD-WHITE",
            "sku": "15000016",
            "name": "Children's Dresser 4-Drawer 'Tidy' White 80x90cm",
            "category": "Furniture",
            "subcategory": "Storage",
            "price": 229.00,
            "in_stock": True,
            "image_url": f"{_IMG}/dresser_child_white.jpg",
            "age_appropriate": ["toddler", "school-age", "teen"],
            "style_tags": ["scandinavian", "minimalist", "clean"],
            "color_palette": ["white", "wood"],
            "room_compatibility": ["bedroom"],
            "image_url": f"{_IMG}/dresser_child_white.jpg",
        },
        {
            "product_id": "CHEST-DRAWERS-MODERN",
            "sku": "15000017",
            "name": "Modern Chest of Drawers 5-Drawer Grey 90x110cm",
            "category": "Furniture",
            "subcategory": "Storage",
            "price": 349.00,
            "in_stock": True,
            "image_url": f"{_IMG}/chest_drawers_modern.jpg",
            "age_appropriate": ["teen", "adult"],
            "style_tags": ["modern", "minimalist", "functional"],
            "color_palette": ["grey", "white"],
            "room_compatibility": ["bedroom", "living room"],
            "image_url": f"{_IMG}/chest_drawers_modern.jpg",
        },
        {
            "product_id": "TOY-STORAGE-CUBE",
            "sku": "15000018",
            "name": "Cube Storage Unit 'Playroom' White 9-Cube with Bins",
            "category": "Furniture",
            "subcategory": "Storage",
            "price": 189.00,
            "in_stock": True,
            "image_url": f"{_IMG}/toy_storage_cube.jpg",
            "age_appropriate": ["toddler", "school-age"],
            "style_tags": ["functional", "playful", "modular"],
            "color_palette": ["white", "multicolor"],
            "room_compatibility": ["bedroom", "playroom"],
            "image_url": f"{_IMG}/toy_storage_cube.jpg",
        },
        # Furniture - Bookshelves
        {
            "product_id": "BOOKSHELF-LOW-CHILD",
            "sku": "15000019",
            "name": "Low Bookshelf 'First Library' Natural Wood 80x80cm",
            "category": "Furniture",
            "subcategory": "Bookshelves",
            "price": 139.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bookshelf_low_child.jpg",
            "age_appropriate": ["toddler", "school-age"],
            "style_tags": ["scandinavian", "natural", "accessible"],
            "color_palette": ["wood", "natural"],
            "room_compatibility": ["bedroom", "playroom"],
            "image_url": f"{_IMG}/bookshelf_low_child.jpg",
        },
        {
            "product_id": "BOOKSHELF-MEDIUM-WHITE",
            "sku": "15000020",
            "name": "4-Tier Bookshelf 'Study Buddy' White 80x140cm",
            "category": "Furniture",
            "subcategory": "Bookshelves",
            "price": 179.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bookshelf_medium_white.jpg",
            "age_appropriate": ["school-age", "teen"],
            "style_tags": ["modern", "minimalist", "functional"],
            "color_palette": ["white", "wood"],
            "room_compatibility": ["bedroom", "office"],
            "image_url": f"{_IMG}/bookshelf_medium_white.jpg",
        },
        {
            "product_id": "BOOKSHELF-TALL-WALNUT",
            "sku": "15000021",
            "name": "Tall Bookshelf 6-Shelf 'Library' Walnut Wood 100x200cm",
            "category": "Furniture",
            "subcategory": "Bookshelves",
            "price": 329.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bookshelf_tall_walnut.jpg",
            "age_appropriate": ["teen", "adult"],
            "style_tags": ["traditional", "wood", "spacious"],
            "color_palette": ["walnut", "wood", "brown"],
            "room_compatibility": ["office", "living room", "bedroom"],
            "image_url": f"{_IMG}/bookshelf_tall_walnut.jpg",
        },
        {
            "product_id": "BOOKSHELF-LADDER-BLACK",
            "sku": "15000022",
            "name": "Ladder Bookshelf 'Industrial Lean' Black Metal 5-Tier",
            "category": "Furniture",
            "subcategory": "Bookshelves",
            "price": 199.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bookshelf_ladder_black.jpg",
            "age_appropriate": ["teen", "adult"],
            "style_tags": ["industrial", "modern", "space-saving"],
            "color_palette": ["black", "metal"],
            "room_compatibility": ["office", "living room", "bedroom"],
            "image_url": f"{_IMG}/bookshelf_ladder_black.jpg",
        },
        {
            "product_id": "BOOKSHELF-CUBE-MODULAR",
            "sku": "15000023",
            "name": "Modular Cube Bookshelf 'Versatile' White 6-Cube",
            "category": "Furniture",
            "subcategory": "Bookshelves",
            "price": 149.00,
            "in_stock": True,
            "image_url": f"{_IMG}/bookshelf_cube_modular.jpg",
            "age_appropriate": ["school-age", "teen", "adult"],
            "style_tags": ["modern", "modular", "flexible"],
            "color_palette": ["white"],
            "room_compatibility": ["bedroom", "office", "living room"],
            "image_url": f"{_IMG}/bookshelf_cube_modular.jpg",
        },
    ]

    CUSTOMER_PROFILE = {
        "language": DEFAULT_LANGUAGE,
        "available_products": None,  # Will be populated after class definition
        "product_catalog_raw": PRODUCT_CATALOG,  # Raw data for tools to access
        "customer_profile": {
            "account_number": f"AN-{random.randint(100000000, 999999999)}",
            "customer_id": "CY-1234-1234",
            "customer_first_name": "Cornelius",
            "customer_last_name": "Koch",
            "email": "Cornelius.koch@example.com",
            "phone_number": "+49-89-555-1234",
            "customer_start_date": "2021-08-15",
            "years_as_customer": 4,
            "billing_address": {
                "street": "ul. Grunwaldzka 472",
                "city": "Berlin",
                "state": "Pomeranian Voivodeship",
                "zip": "80-309",
                "country": "PL",
            },
            "shipping_address": {
                "street": "ul. Grunwaldzka 472",
                "city": "Berlin",
                "state": "Pomeranian Voivodeship",
                "zip": "80-309",
                "country": "PL",
            },
            "order_history": [
                {
                    "order_id": f"ORD-{random.randint(10000, 99999)}",
                    "date": "2023-05-20",
                    "items": [
                        {
                            "product_id": "SAM-TV-QE55QN90B",
                            "sku": "2789123",
                            "name": "Samsung QE55QN90B Neo QLED TV",
                            "quantity": 1,
                            "type": "product",
                            "price": 1599.00,
                        },
                        {
                            "product_id": "PLUSGARANTIE-TV-3J",
                            "sku": "8765432",
                            "name": "Extended warranty 3 years for TV up to 1650 EUR",
                            "quantity": 1,
                            "type": "service",
                            "price": 139.00,
                        },
                    ],
                    "total_amount": 1738.00,
                    "store_id": "CY-BER-CENTER",
                    "channel": "instore",
                },
                {
                    "order_id": f"ORD-{random.randint(10000, 99999)}",
                    "date": "2023-11-10",
                    "items": [
                        {
                            "product_id": "SONY-WH1000XM5S",
                            "sku": "2812345",
                            "name": "Sony WH-1000XM5 Noise-Cancelling Headphones",
                            "quantity": 1,
                            "type": "product",
                            "price": 369.00,
                        }
                    ],
                    "total_amount": 369.00,
                    "store_id": "CY-BER-CENTER",
                    "channel": "instore",
                },
                {
                    "order_id": f"ORD-{random.randint(10000, 99999)}",
                    "date": "2024-03-01",
                    "items": [
                        {
                            "product_id": "LOGI-MX-MASTER3S",
                            "sku": "2754678",
                            "name": "Logitech MX Master 3S Performance Mouse",
                            "quantity": 1,
                            "type": "product",
                            "price": 105.00,
                        },
                        {
                            "product_id": "ANKER-POWERCORE-20K",
                            "sku": "2699887",
                            "name": "Anker PowerCore III 20000mAh Power Bank",
                            "quantity": 1,
                            "type": "product",
                            "price": 49.00,
                        },
                    ],
                    "total_amount": 154.00,
                    "store_id": "CY-BER-CENTER",
                    "channel": "instore",
                },
            ],
            "current_cart": {
                "cart_id": f"CART-{random.randint(100000, 999999)}",
                "items": [
                    {
                        "product_id": "GENERIC-PIXEL-CASE",
                        "sku": "1122334",
                        "name": "Generic Google Pixel Case",
                        "quantity": 1,
                        "price": 19,
                    },
                ],
                "subtotal": 19,  # Adjust subtotal accordingly
                "last_updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            },
            "loyalty_points": 133,
            "preferred_store": "Cymbal Berlin",
            "communication_preferences": {
                "email": True,
                "sms": True,
                "push_notifications": False,
            },
            "loyalty_program": {
                "program_name": "myCymbal",
                "card_number": f"2951 {random.randint(1000, 9999)} {random.randint(1000, 9999)} {random.randint(1000, 9999)}",
                "member_since": "2021-08-15",
                "points_balance": 2150,
                "level": "Standard",
                "digital_receipts_enabled": True,
                "exclusive_offers_available": 2,
                "communication_preferences": {
                    "email": True,
                    "sms": True,
                    "push_notifications": False,
                },
            },
            "interests": [
                "Smart Home",
                "Audio",
                "Mobile Computing",
                "Photography",
            ],
            "registered_devices": [
                {
                    "product_id": "SAM-TV-QE55QN90B",
                    "name": "Samsung QE55QN90B Neo QLED TV",
                    "purchase_date": "2023-05-20",
                    "warranty_expires": "2026-05-19",
                    "has_extended_warranty": True,
                },
                {
                    "product_id": "SONY-WH1000XM5S",
                    "name": "Sony WH-1000XM5",
                    "purchase_date": "2023-11-10",
                    "warranty_expires": "2025-11-09",
                    "has_extended_warranty": False,
                },
            ],
            "scheduled_appointments": {
                "appointment_id": f"APP-{random.randint(1000, 9999)}",
                "service_type": "Smartphone Repair Drop-off",
                "date_time": "2025-04-18 14:00:00",
                "store_id": "CY-BERLIN",
                "status": "Scheduled",
            },
        },
        "current_datetime": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }


# Format product catalog as readable markdown table for the model


def _format_product_catalog_slim():
    """Format a slim product catalog summary to reduce context tokens.

    Instead of listing all 130 products (~12K tokens), provides a
    category summary (~500 tokens) and tells the model to use tools
    for product lookup.
    """
    # Count by category
    categories = {}
    for product in RetailContext.PRODUCT_CATALOG:
        cat = product.get("category", "Other")
        if cat not in categories:
            categories[cat] = {"count": 0, "price_min": float("inf"), "price_max": 0}
        categories[cat]["count"] += 1
        price = product.get("price", 0)
        categories[cat]["price_min"] = min(categories[cat]["price_min"], price)
        categories[cat]["price_max"] = max(categories[cat]["price_max"], price)

    lines = [
        f"Product catalog: {len(RetailContext.PRODUCT_CATALOG)} products across {len(categories)} categories.",
        "",
        "| Category | Products | Price Range (EUR) |",
        "|----------|----------|-------------------|",
    ]
    for cat, info in sorted(categories.items()):
        lines.append(
            f"| {cat} | {info['count']} | {info['price_min']:.0f} - {info['price_max']:.0f} |"
        )

    lines.append("")
    lines.append(
        "Use get_product_recommendations, check_product_availability, or "
        "display_product_search_results tools to find specific products. "
        "Do NOT list products from memory -- always use tools for accurate data."
    )

    return "\n".join(lines)


# Populate the available_products field with slim catalog summary
RetailContext.CUSTOMER_PROFILE["available_products"] = _format_product_catalog_slim()


def create_customer_profile(
    customer_id=None, first_name=None, last_name=None, email=None
):
    """
    Create a dynamic customer profile based on provided customer information.
    If no information is provided, returns the default profile.

    Args:
        customer_id: Customer ID (e.g., "CY-1234-5678")
        first_name: Customer's first name
        last_name: Customer's last name
        email: Customer's email address

    Returns:
        dict: Customer profile with personalized information
    """
    # Start with a copy of the default profile
    import copy

    profile = copy.deepcopy(RetailContext.CUSTOMER_PROFILE)

    # Update with provided customer information
    if customer_id:
        profile["customer_profile"]["customer_id"] = customer_id
    if first_name:
        profile["customer_profile"]["customer_first_name"] = first_name
    if last_name:
        profile["customer_profile"]["customer_last_name"] = last_name
    if email:
        profile["customer_profile"]["email"] = email

    # For new customers (not the default), clear order history and adjust
    # other fields
    if customer_id and customer_id != "CY-1234-1234":
        # New customer - clear historical data
        profile["customer_profile"]["order_history"] = []
        profile["customer_profile"]["loyalty_points"] = 0
        profile["customer_profile"]["loyalty_program"]["points_balance"] = 0
        profile["customer_profile"]["registered_devices"] = []
        profile["customer_profile"]["scheduled_appointments"] = {}
        profile["customer_profile"]["current_cart"]["items"] = []
        profile["customer_profile"]["current_cart"]["subtotal"] = 0
        # Update customer start date to today
        profile["customer_profile"]["customer_start_date"] = datetime.now().strftime(
            "%Y-%m-%d"
        )
        profile["customer_profile"]["loyalty_program"][
            "member_since"
        ] = datetime.now().strftime("%Y-%m-%d")
        profile["customer_profile"]["years_as_customer"] = 0

    return profile
